### ISSUE TITLE
NPE on write error

### ISSUE THREAD

**Issue by j-white** [InfluxCommunity/influxdb3-java#147]
### Specifications

* Client Version: 0.8.0
* InfluxDB Version: InfluxDB Edge (snapshot)
* Platform: MacOS

### Code sample to reproduce problem

```java
influxDBClient.writePoints(points);
```

### Expected behavior

Fail with a descriptive exception

### Actual behavior

Fail with an NPE

### Additional info

Body from HTTP response looks like:
```
{"error":"parsing failed for write_lp endpoint","data":{"original_line":"sample sample_interval=30,value=0 1715274737218000000","line_number":1,"error_message":"invalid field value in line protocol for field 'sample_interval' on line 0: expected type iox::column_type::field::integer, but got iox::column_type::field::float"}}
```

Which triggers this exception:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at com.influxdb.v3.client.internal.RestClient.request(RestClient.java:179)
	at com.influxdb.v3.client.internal.InfluxDBClientImpl.writeData(InfluxDBClientImpl.java:323)
	at com.influxdb.v3.client.internal.InfluxDBClientImpl.writePoints(InfluxDBClientImpl.java:157)
	at com.influxdb.v3.client.internal.InfluxDBClientImpl.writePoints(InfluxDBClientImpl.java:152)
	at com.influxdb.v3.client.InfluxClientFactory_ProducerMethod_newClient_Ux0i73pEPhnEmmdrKxjBuioA9j8_ClientProxy.writePoints(Unknown Source)
```

Relevant code block: https://github.com/InfluxCommunity/influxdb3-java/blob/v0.8.0/src/main/java/com/influxdb/v3/client/internal/RestClient.java#L179

**Comment by bednar** [comment]
Hi @j-white,

Thank you for using our client.

Would you be interested in contributing to this issue? We welcome all pull requests and would be happy to review your submission. If not, we will address the issue as soon as possible.

Best regards
