### ISSUE TITLE
ClientConfig: proxy property of ClientConfig leads to IOException when used 

### ISSUE THREAD

**Issue by karel-rehor** [InfluxCommunity/influxdb3-java#91]
### Specifications

* Client Version: 0.5.0-Snapshot
* InfluxDB Version: IoX
* Platform: Ubuntu 22.04, openjdk 17.0.9 with Envoy 1.26 (docker)

### Code sample to reproduce problem

```java

// N.B. this needs to be run with envoy proxy at port 10000

  public static void main(String[] args) throws IOException {
    ClientConfig config = new ClientConfig.Builder()
      .host(Props.getHost())
    //  .host("http://localhost:10000")
      .token(Props.getToken())
      .database(Props.getBucket())
      .proxy(ProxySelector.of(new InetSocketAddress ("localhost", 10000)))
      .build();

    InfluxDBClient client = InfluxDBClient.getInstance(config);
    
    Point point = StandardItems.getPointBird();

    System.out.println("DEBUG writing over proxy " + point.toLineProtocol());
    client.writePoint(point);
    System.out.println("Success");
    
    Query.DumpBirds(client);
    
  }

```

### Expected behavior

Expected the request to be passed through the proxy, just as it gets passed through when calling the proxy directly as if it were the host.  See the commented line in the code sample section.

### Actual behavior

Generates an exception.  

```
Exception in thread "main" com.influxdb.v3.client.InfluxDBApiException: java.io.IOException: Tunnel failed, got: 404
	at com.influxdb.v3.client.internal.RestClient.request(RestClient.java:170)
	at com.influxdb.v3.client.internal.InfluxDBClientImpl.writeData(InfluxDBClientImpl.java:256)
	at com.influxdb.v3.client.internal.InfluxDBClientImpl.writePoints(InfluxDBClientImpl.java:133)
	at com.influxdb.v3.client.internal.InfluxDBClientImpl.writePoint(InfluxDBClientImpl.java:123)
	at com.influxdb.v3.client.internal.InfluxDBClientImpl.writePoint(InfluxDBClientImpl.java:114)
	at io.bonitoo.qa.ClientWithProxy.main(ClientWithProxy.java:33)
Caused by: java.io.IOException: Tunnel failed, got: 404
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at com.influxdb.v3.client.internal.RestClient.request(RestClient.java:168)
	... 5 more
Caused by: java.io.IOException: Tunnel failed, got: 404
	at java.net.http/jdk.internal.net.http.PlainTunnelingConnection.lambda$connectAsync$2(PlainTunnelingConnection.java:96)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.handle(Http1Response.java:695)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.handle(Http1Response.java:621)
	at java.net.http/jdk.internal.net.http.Http1Response$Receiver.accept(Http1Response.java:612)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.tryAsyncReceive(Http1Response.java:668)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:233)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

and this is reflected in the Proxy server log 

```
scripts-envoy-1  | [2024-01-16T12:45:35.722Z] "CONNECT - HTTP/1.1" 404 NR 0 0 0 - "-" "-" "975ff2d8-81e2-4af0-8943-940e1d1fd69f" "us-east-1-1.aws.cloud2.influxdata.com:443" "-"
```

### Additional info

Note the issue may be in the proxy configuration (attached), however calling the proxy directly as in the following code works without issue.  In any event this issue needs to be reexamined at as soon as time permits.

```java
  public static void main(String[] args) throws IOException {
    ClientConfig config = new ClientConfig.Builder()
    //  .host(Props.getHost())
      .host("http://localhost:10000")
      .token(Props.getToken())
      .database(Props.getBucket())
   //   .proxy(ProxySelector.of(new InetSocketAddress ("localhost", 10000)))
      .build();

    InfluxDBClient client = InfluxDBClient.getInstance(config);

    Point point = StandardItems.getPointBird();

    System.out.println("DEBUG writing over proxy " + point.toLineProtocol());
    client.writePoint(point);
    System.out.println("Success");

    Query.DumpBirds(client);

  }
```
[docker-compose.yml.txt](https://github.com/InfluxCommunity/influxdb3-java/files/13950208/docker-compose.yml.txt)
[envoy.yaml.txt](https://github.com/InfluxCommunity/influxdb3-java/files/13950209/envoy.yaml.txt)

**N.B.** **The example** in the comment in `ClientConfig.java:72` **is misleading**.  

```java
/*
...
 *     .gzipThreshold(4096)
 *     .proxy(ProxySelector.of(new InetSocketAddress("http://proxy.local", 8888)))
 *     .build();
 */
```

In a test implementation, using a String value for the InetSocketAddress constructor with the leading "http://" protocol leads to a `java.net.URISyntaxException`

e.g.
```
java.io.IOException: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 20: proxy.https://[http://localhost]:10000/
```

**Comment by karel-rehor** [comment]
Also note: in the nodejs client library the option `proxyUrl` which is a _cognate_ to `ClientConfig.proxy` in the java client library, works with the same envoy proxy configuration without issue.

**Comment by alespour** [comment]
Indeed Envoy with the provided configuration _does not work for Java `HttpClient`_.

I tried Squid with the simplest configuration possible and the example with proxy works.

`squid.conf`:
```
http_port 3128
http_access allow all
```

`docker run --name squid --rm -it -p 3128:3128 -v ./squid.conf:/etc/squid/squid.conf sameersbn/squid:latest`

```java
    .proxy(ProxySelector.of(new InetSocketAddress ("localhost", 3128))
```

I have no idea how to configure Envoy properly for this library, its insanely complicated.

---

I have fixed the wrong example in `ClientConfig.java:72` javadoc in #[c274d37](https://github.com/InfluxCommunity/influxdb3-java/commit/c274d374d89030d0d1d3f51552d2c8c90c4cfedf)

**Comment by alespour** [comment]
Found a config solution that works with the above example (in [envoy/issues/11552](https://github.com/envoyproxy/envoy/issues/11552#issuecomment-1550113759)): 

[envoy.yaml.txt](https://github.com/InfluxCommunity/influxdb3-java/files/13978642/envoy.yaml.txt)
